### ISSUE TITLE
Milestone 3 Objectives

### ISSUE THREAD

**Issue by jinxuan-owyong** [FindNUS/frontend#77]
__Sprint #__ 4/5

__Expected completion:__ 25/07/2022

__Tasks to be completed__:

#### User experience
- [x] Responsive page design for use with mobile and tablet
- [x] SMS/Email (un)subscription for backend [lookout service](https://findnus.github.io/ms2/ms3/#lookout-service)
- [x] Edit: Allow users to enter 8-digit Singapore mobile numbers (#76)
- [x] Edit: Expand filter options to include date
- [x] Edit: Pagination for peek items, allow users to choose items to view per page 
- [x] Edit: Show similar items when viewing an item

#### Geocoding
- [x] Implement geocoding with Google Maps API, which translates user input into GPS coordinates
- [x] Integrate map into application and allow user to view item location and get directions

#### Application Testing
- [x] Extend unit testing to cover all components (#79)
- [ ] Extend integration testing to cover all pages
- [ ] End-to-end testing with [Puppeteer](https://www.npmjs.com/package/puppeteer) to simulate user intertaction with application
